name: CI

on:
  push:
    branches: [ main, Short-term ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov pyyaml
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff dynamic_cli_builder test || true # fail softly for now
      - name: Run tests with coverage
        run: |
          pytest --cov=dynamic_cli_builder --cov-fail-under=75
