name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # manual version tags still trigger publishmain

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pyyaml

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Run Tests
        run: |
          pip install pytest
          pytest -q

      - name: Bump version & create tag (semantic-release)
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install python-semantic-release
          semantic-release version --no-push --changelog --skip-ci-tag
          git push --follow-tags

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
